### ISSUE TITLE
query

### ISSUE THREAD

**Issue by Myshiro** [WhimsicalDragon/TwitchUsernameChecker#1]
how do i use it

**Comment by WhimsicalDragon** [comment]
You will need to setup a twitch developer account. Once you do that you need to make a twitch app and get your client secret and client id. You can use the exconfig.py file as base. Rename the file to config.py and put in your client id and client secret.
![image](https://user-images.githubusercontent.com/40681291/180390349-b12e8470-90a4-4ae1-a1d3-527e356d6bb0.png) After that all you have to do is change the CHANNEL variable in usernameChecker.py to the desired username.

Please let me know if there is any clarification needed.

**Comment by WhimsicalDragon** [comment]
Closing since no reply
